### PR TITLE
New bebop commands

### PR DESCRIPTION
**Pull request by Victor804**
I added 3 functions for bebop:
1) change the max altitude 
2) change the max tilt
3) Move the drone by a distance in meters

### CODE REVIEW

**Comment by amymcgovern** [comment]
I actually added move by just about an hour ago.  I find it VERY unreliable and dangerous.  It left it in but with comments to not use.  I've got a pending post on the developer's forum about it.

**Comment by amymcgovern** [comment]
p.s. I'll take the tilt and altitude commands if you can make those a separate push.

**Comment by Victor804** [comment]
I just saw your message on move by. I've been able to use it a few times. And I once had a problem but I didn't know where it came from. Can you give me the link to your post on developer's forum to keep me informed?
For the tilt and altitude commands I do it as soon as possible.

**Comment by amymcgovern** [comment]
http://forum.developer.parrot.com/t/moveby-command-error-on-bebop-2/7630/2

**Comment by amymcgovern** [comment]
It went sort of crazy.  Our code is almost identical except I added a sleep until the command finishes.  It sends a packet saying it is done.  The code is in the codebase now - I just wouldn't use it!

**Comment by amymcgovern** [comment]
I did some searches on the forum and saw others complaining about similar behavior.  It simply went nuts.  It would always do the command right but then 50% of the time, it would take off across the room at nearly full speed!!

**Comment by Victor804** [comment]
In my case I pushed it forward 1m then I landed it. It was only at the next takeoff that the drone accelerated up 3 times and then fell  :'( 
Happily nothing broken  : )

Indeed I think it can be really dangerous !

**Comment by amymcgovern** [comment]
Glad nothing broke!  We broke a propeller guard but nothing serious.

**Comment by Victor804** [comment]
I revert the commit "added move by for bebop". I think that's good ?

**Comment by amymcgovern** [comment]
Ok and it is in the pypi distribution with the docs for the new commands also.

**Comment by amymcgovern** [comment]
@Victor804 We spent a long time today on this and found the issue in the firmware causing it to shoot off randomly.  Parrot confirmed it on the development board and said they will fix.  In the meantime, the key is turning off the GPS (if you have a bebop 1) or ensuring the GPS doesn't alternate between getting a lock and then losing it (if you are indoors).  Parrot suggested and we tried tin foil and it worked great.  Wanted you to know.  The move_relative command is in bebop as I never took it out.

**Comment by Victor804** [comment]
Thanks a lot @amymcgovern I'll try as soon as possible.

**Pull request merged**
