### PR TITLE
Minidrone

### PR DESCRIPTION
**Pull request by Victor804**
I changed the Mambo file to be compatible with all Minidrones parrot (including parrot swing). I added an example for the swing and some specific control for the swing parrot .[Parrot Swing](https://www.parrot.com/fr/minidrones/parrot-swing#parrot-swing)

### CODE REVIEW

**Comment by amymcgovern** [comment]
Going to catch up on these after the drone competition this week.  Multiple people using the library and I don't want to make changes during competition.

**Comment by Victor804** [comment]
I modified the documentation to be compatible with the swing parrot.
I'll let you tell me if this is good.

**Comment by amymcgovern** [comment]
Ok, I'm back from the competition and looking at this.  I don't know that I want to refactor Mambo quite this dramatically.  I also don't have a swing to test on.  I'm concerned about the major refactoring and backwards compatibility issues here (with introducing new classes, etc).  Honestly if I was re-writing pyparrot now, I would make a single Drone class instead of a separate Bebop and Mambo class but it is what it is for now.  Also, I rather dislike that GitHub won't let me accept only parts of the code.  So I can't take what I like and then edit the rest.  I'm happy to support the swing.  How shall we handle this?

**Comment by marcosboggia** [comment]
Hi @Victor804. Are you planning on adding download picture feature over BLE?

**Comment by amymcgovern** [comment]
The more I look at this, the more I like the implementation.  Very clean.  I'll work on integrating it and putting out the new code on pypi!  Very nice.

**Comment by Victor804** [comment]
Hi,
Thanks @amymcgovern 😀.
@marcosboggia Sorry, I can't help you right now.

**Comment by amymcgovern** [comment]
Going to integrate this right now.  Sorry it took so long!  Been very busy with travel.  I'll accept the changes and then get the official new version pushed out within an hour.

**Comment by Victor804** [comment]
Great. Thank you so much.

**Comment by amymcgovern** [comment]
It's live!  I just pushed version 1.5.0 to pip.

**Comment by amymcgovern** [comment]
Had to make it a major version change (from 1.4 to 1.5) since you did break backwards compatibility a tiny bit (just with the import).  However, I really like the approach of Minidrone.

**Pull request merged**
