### PR TITLE
Corrected parsing sensor data to get all values

### PR DESCRIPTION
**Pull request by awmt102**
Previously parsing the sensor data for a group of similar sensors would only store the first one (e.g. speedX from speedX, speedY and speedZ). Now all values are extracted and stored in dictionary.

Tested both Attitude and Speed sets. Both appear to work, although accuracy of values is unknown.

Also added .gitignore file.

Tested on Windows7 with Bebop. Untested with Mambo.

### CODE REVIEW

**Comment by amymcgovern** [comment]
Thanks!  I'm going to integrate this into the develop branch, ensure the fix also works on the mambo, and then I'll push it back into master.

**Comment by awmt102** [comment]
OK. I'm fairly new to Github so not entirely au fait with differences between master and develop and whether I need to be doing anything differently in the future... but I'm learning. I might add a few 'issues' and work on them over the coming weeks... hopefully some of the things i have learnt from katarina will be useful.

**Comment by amymcgovern** [comment]
I'm new to the gitflow idea of master/develop branches so I've been trying to figure out how to integrate your changes one file at a time (seems not possible).  I've had a busy week so haven't had a chance to fix it.  Hopefully tonight.

**Comment by amymcgovern** [comment]
I fixed the parser for the Mambo and also corrected your code (so you should grab the latest).  it wasn't handling the different packet sizes right (but that is fixed now and tested on the mambo)

**Pull request merged**
